# Default CMake configuration for TweetNaCl-Modular

set(BUILD_SHARED_LIBS ON)
set(BUILD_STATIC_LIBS ON)
set(BUILD_TESTS ON)
set(BUILD_APP ON)
set(ENABLE_DRNG ON)
set(ENABLE_PQC ON)
set(ENABLE_FIPS_MODE OFF)
set(ENABLE_COVERAGE OFF)
set(ENABLE_SANITIZERS OFF)
set(ENABLE_LTO OFF)
set(NACL_RUNTIME_DISPATCH OFF)
set(NACL_STATIC_IMPL OFF)
