# x86 32-bit (i686) cross-compilation toolchain
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i686)

if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "i686|i386")
    set(CMAKE_C_COMPILER cc)
    set(CMAKE_CXX_COMPILER c++)
else()
    set(CMAKE_C_COMPILER gcc)
    set(CMAKE_CXX_COMPILER g++)
    set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -m32")
    set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -m32")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Architecture-specific optimizations
set(CMAKE_C_FLAGS_INIT "-march=i686 -mtune=generic ${CMAKE_C_FLAGS_INIT}")
